// src/agents/orchestrator.js
import { callAI, safeParseJSON } from '../utils/ai.js'
import { runPython } from '../utils/python.js'
import { getCodeWriterPrompt } from '../engines/prompts.js'

export async function getRecommendedCategories(profile) {
  try {
    const reply = await callAI({
      maxTokens: 300,
      system: `You are a data analysis expert. Given a dataset profile, return a JSON array of analysis category IDs.
ALWAYS include: ["charts","eda","data_quality","report"]
Add ONLY when data supports them:
- "regression" if numeric prediction target likely exists
- "ml_models" if >100 rows and multiple columns for ML
- "stats_tests" if categorical group columns exist
- "financial" if columns suggest prices, returns, revenue, profit, stock, P&L, yield, close, open
- "marketing" if columns suggest customer, sales, order, CLV, churn, RFM, campaign, CAC
- "hr" if columns suggest employee, salary, attrition, headcount, department, tenure
- "operations" if columns suggest inventory, production, OEE, defect, units, SKU, machine
- "text_nlp" if any column has many long text strings
Return ONLY a valid JSON array. No explanation.`,
      user: `Dataset profile:\n${profile.summary}`
    })
    const parsed = safeParseJSON(reply)
    if (Array.isArray(parsed)) {
      const core = ['charts','eda','data_quality','report']
      return [...new Set([...core, ...parsed])]
    }
  } catch(e) { console.warn('Category recommendation failed:', e) }
  return ['charts','eda','data_quality','report']
}

export async function runAnalysis({ category, choices, filteredData, profile }) {
  if (!filteredData || filteredData.length === 0) {
    throw new Error('No data to analyse. Check your slicer filters.')
  }

  // Fire code writer and chart designer in parallel
  const [pythonCode, chartConfigRaw] = await Promise.all([
    callAI({
      maxTokens: 2000,
      system: getCodeWriterPrompt(category),
      user: `Dataset profile:\n${profile.summary}\n\nUser selected:\n${JSON.stringify(choices, null, 2)}\n\nRows: ${filteredData.length}\n\nRules: df is the DataFrame. Last line must be a bare dict variable (NO return statement). All values JSON-serialisable.`
    }),
    callAI({
      maxTokens: 400,
      system: `Design a Recharts chart config. Return ONLY JSON: { "type": "bar"|"line"|"scatter"|"pie"|"area", "xKey": "colname", "yKeys": ["col1"], "title": "title", "colorBy": null }. Use only actual column names from the profile.`,
      user: `Columns: ${JSON.stringify(Object.keys(profile.columns))}\nTypes: ${JSON.stringify(Object.fromEntries(Object.entries(profile.columns).map(([k,v])=>[k,v.type])))}\nCategory: ${category}\nChoices: ${JSON.stringify(choices)}`
    })
  ])

  // Execute Python
  let executionResult = await runPython(pythonCode, filteredData)

  // Auto-fix Python errors
  if (executionResult?.__error) {
    console.warn('Python error, asking AI to fix:', executionResult.__error)
    try {
      const fixedCode = await callAI({
        maxTokens: 1500,
        system: 'Fix this Python error. Return ONLY corrected Python code. No markdown. No return statements at top level.',
        user: `Code:\n${executionResult.__code}\n\nError:\n${executionResult.__error}`
      })
      executionResult = await runPython(fixedCode, filteredData)
      if (executionResult?.__error) {
        executionResult = { error: 'Analysis could not complete. Try different variable selections.' }
      }
    } catch(e) {
      executionResult = { error: 'Analysis failed: ' + e.message }
    }
  }

  const resultSummary = JSON.stringify(executionResult || {}).slice(0, 1200)

  // Fire interpreter + recommender + column saver in parallel
  const [explanation, nextStepsRaw, newColumnsRaw] = await Promise.all([
    callAI({
      maxTokens: 250,
      system: 'Explain data analysis results to a non-technical business user. Be specific, use actual numbers. Max 3 sentences. Plain English. Start with the most important finding.',
      user: `Analysis: ${category}. Choices: ${JSON.stringify(choices)}. Results: ${resultSummary}`
    }),
    callAI({
      maxTokens: 350,
      system: 'Suggest 4 specific next analysis steps. Reference actual column names. Return ONLY a JSON array of 4 strings. No generic advice.',
      user: `Just ran: ${category}. Results: ${resultSummary}. Available columns: ${Object.keys(profile.columns).join(', ')}`
    }),
    callAI({
      maxTokens: 200,
      system: 'Identify new columns generated by this analysis to save to dataset memory. Return JSON: {"columns":[{"name":"colName","description":"what it is"}]}. Return {"columns":[]} if none. Return ONLY JSON.',
      user: `Analysis: ${category}. Result keys: ${Object.keys(executionResult||{}).join(', ')}. Choices: ${JSON.stringify(choices)}`
    })
  ])

  return {
    id: Date.now(),
    category, choices,
    result: executionResult,
    chartConfig: safeParseJSON(chartConfigRaw),
    explanation: explanation || 'Analysis complete.',
    nextSteps: safeParseJSON(nextStepsRaw) || [],
    newColumns: safeParseJSON(newColumnsRaw)?.columns || [],
    timestamp: new Date().toISOString(),
    rowCount: filteredData.length
  }
}
